version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "nested-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1wcc1rlbjeh9t"
s3_prefix = "nested-stack"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
